### ISSUE TITLE
Rename repo, language and IR for Public Beta

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydro#1571]
- Our repo is called `hydroflow` but it's really the monorepo for all of Hydro, and should be renamed before public beta.
- We should pick well-distinguished final names for the high-level language and the IR. Proposal is "Hydro" and "Lodro" or "Hydroflow" and "Lodroflow".
- We then need to fix all the directory names, file names and documentation to reflect these final names.

**Comment by jhellerstein** [comment]
Something generic like DataflowIR would make use seem like de facto solution.

**Comment by jhellerstein** [comment]
Decisions:
- Hydroflow => DFIR (DataFlow IR)
- Hydroflow+ => Hydro

**Comment by MingweiSamuel** [comment]
hydroflow -> dfir_rs
hydroflow_* -> dfir_*
hydroflow_plus -> hydro_lang (?)
hydorflow_plus_* -> hydro_*
lattice -> algebraic or modern algebra something hold off for now

**Comment by MingweiSamuel** [comment]
Renames were as follows:
```
hydroflow -> dfir_rs
hydroflow_lang -> dfir_lang
hydroflow_macro -> dfir_macro
hydroflow_plus -> hydro_lang
hydroflow_plus_std -> hydro_std
hydroflow_datalog -> dfir_datalog
hydroflow_datalog_core -> dfir_datalog_core
```
#1617
#1620
#1621
