### ISSUE TITLE
Telemetry: local and global

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydro#928]
Code:
- [ ] Associate hydroflow+ functions with hydroflow syntax for flamegraphs: https://github.com/hydro-project/hydroflow/issues/1268
- [x] #1269
- [ ] #1270
    - What kind of throughput are we getting
    - (source or sink op id, tick, bytes, messages), time elapsed per tick

Tasks:
- [ ] Figure out how perf flamegraphs work with idle time
- [ ] Measure overhead from profiling

---

- Need a way to get fine-grained telemetry and control over its aggregation/publishing within a transducer
- Need ways to collect/aggregate telemetry across transducers
   - write to S3/etc
   - a library like Anna KVS with telemetry keys, sketch lattices, etc.
- Telemetry standards and third-party tools
- Beware of self-measurement abberations

While designing, think about what would make this a differentiating and general-purpose value-add of Hydro. Compare to Dapper etc for collection/aggregation.

**Comment by MingweiSamuel** [comment]
Tiemo:
* How can I know when a batch of data is fully processed? (#834)
   * Right now, have to implement a tombstone to signal EOS
   * Have design patterns for termination detection
   * (Have general-purpose termination detection as a std library?)

**Comment by MingweiSamuel** [comment]
#834 related

**Comment by rohitkulshreshtha** [comment]
Next steps: Check with David re: metrics.

**Comment by MingweiSamuel** [comment]
Closing, just about done, see small issues above
